### ISSUE TITLE
hello, dataset can't download now

### ISSUE THREAD

**Issue by wangru1992** [oppo-us-research/PoP-Net#3]
I use bittorrent and there is a warning "possibly insufficent sources", and I wait for a lot of time there are 0.0% downloaded.

**Comment by deleike410** [comment]
Same  problem.  0.0%
![1654677494(1)](https://user-images.githubusercontent.com/33301898/172571867-d6547470-a233-4c18-b86f-0f59215e502b.png)

**Comment by lizhong3232** [comment]
Apology for the inconvenience, now the data is reseeded.

**Comment by sean1090** [comment]
I download the seed file but it always being 0.00%.

**Comment by calvindu95** [comment]
> 

what software are you using right now? I have no problem when i try to download it today.

**Comment by sean1090** [comment]
Really? I use utorrent  and bittorrent , the valid seed resource is 0. What about you,thanks

**Comment by calvindu95** [comment]
> Really? I use utorrent and bittorrent , the valid seed resource is 0. What about you,thanks

We are trying to make the seed again, I will let you know when the new torrent is ready.

**Comment by reddog3s** [comment]
Hello, when will new torrent be ready? I'm facing the same issue right now. I can't download dataset by bittorrent because seed resource is 0

**Comment by calvindu95** [comment]
Hi, we are trying to add another method to help you download the dataset, my colleague is working on it. We would launch it ASAP.

> Hello, when will new torrent be ready? I'm facing the same issue right. I can't download dataset by bittorrent because sees resource is 0

**Comment by joschuck** [comment]
Do you have any updates on this?

**Comment by calvindu95** [comment]
> Do you have any updates on this?

Our engineer in charge of the dataset is on leave, he would back next Monday. Will update at that time

**Comment by calvindu95** [comment]
> > Do you have any updates on this?
> 
> Our engineer in charge of the dataset is on leave, he would back next Monday. Will update you at that time

@joschuck Our engineer will fix them tonight, could you check whether the torrent is good to use tomorrow morning?

**Comment by joschuck** [comment]
Sure, will check in the afternoon from Oslo timezone! 🙏

**Comment by joschuck** [comment]
hi, not getting any seed unfortunately :(

**Comment by calvindu95** [comment]
> hi, not getting any seed unfortunately :(

our engineer tried it, and it works. He would double-check the issue. 
And he notifies me that "Make sure they have this tracker: udp://tracker.opentrackr.org:1337/announce"

**Comment by joschuck** [comment]
Thank you guys! Seems to be up and running and I am downloading it now!

**Comment by alexj94** [comment]
Hi, it seems that the torrent link has to be reseeded another time. I can't download the dataset right now.

**Comment by lizhong3232** [comment]
close as completed
