### ISSUE TITLE
Unable to download the Dataset using BitTorrent file

### ISSUE THREAD

**Issue by Shreyas-NR** [oppo-us-research/PoP-Net#4]
Could you please reseed the data? or share an alternate method to get the dataset?

**Comment by lizhong3232** [comment]
Apology for the inconvenience, now the data is reseeded.

**Comment by Shreyas-NR** [comment]
Hi @lizhong3232,
The part 2 and part 3 files seems to be corrupted. Could you please once check at your end?

![image](https://user-images.githubusercontent.com/58805235/182295737-8076da30-a1e8-461c-ae2f-fbd5eb5611bf.png)

`$ 7z l ardata.7z.002

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,32 CPUs Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz (406F1),ASM,AES-NI)

Scanning the drive for archives:
1 file, 24159191040 bytes (23 GiB)

Listing archive: ardata.7z.002


ERROR: ardata.7z.002 : Can not open the file as archive



Errors: 1
`

**Comment by calvindu95** [comment]
> Hi @lizhong3232, The part 2 and part 3 files seems to be corrupted. Could you please once check at your end?
> 
> ![image](https://user-images.githubusercontent.com/58805235/182295737-8076da30-a1e8-461c-ae2f-fbd5eb5611bf.png)
> 
> `$ 7z l ardata.7z.002
> 
> 7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21 p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,32 CPUs Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz (406F1),ASM,AES-NI)
> 
> Scanning the drive for archives: 1 file, 24159191040 bytes (23 GiB)
> 
> Listing archive: ardata.7z.002
> 
> ERROR: ardata.7z.002 : Can not open the file as archive
> 
> Errors: 1 `

Hi, you only need to unzip ardata.7z.001, 7z like that will find the others automatically. Does this work for you?

**Comment by Shreyas-NR** [comment]
> Hi, you only need to unzip ardata.7z.001, 7z like that will find the others automatically. Does this work for you?

Hi @calvindu95 ,
Yes, I am able to extract the complete dataset. 

Thank you!

**Comment by smidm** [comment]
There are no seeders currently.

**Comment by smidm** [comment]
The two online peers have only 26.6% of data available.

![image](https://github.com/oppo-us-research/PoP-Net/assets/820292/4f278069-cc92-4fd3-b001-8e9e89bd483a)

**Comment by smidm** [comment]
thanks, I've downloaded the dataset
