### ISSUE TITLE
License info?

### ISSUE THREAD

**Issue by ogencoglu** [oppo-us-research/PoP-Net#7]
What is the license of the dataset?

**Comment by brmurali** [comment]
@oppo-us-research 
What is the license of this dataset?

**Comment by lizhong3232** [comment]
We are working on it, thx for asking

**Comment by calvindu95** [comment]
> What is the license of the dataset?

PoP-Net is licensed under the Apache License 2.0

**Comment by calvindu95** [comment]
> What is the license of the dataset?

PoP-Net is licensed under the Apache License 2.0
